# https://github.com/ftonneau/tangere-terminal/blob/main/install/install.md

foreground = #fdfdd9
background = #1a2938
palette = 0=#000000
palette = 1=#f2826d
palette = 2=#6dafb5
palette = 3=#e0ba70
palette = 4=#8fb4cd
palette = 5=#bb98d9
palette = 6=#b2babf
palette = 7=#e6e4d3
palette = 8=#b3b3b3
palette = 9=#f2826d
palette = 10=#6dafb5
palette = 11=#ffdd99
palette = 12=#8fb4cd
palette = 13=#bb98d9
palette = 14=#a9c9cc
palette = 15=#2f4656
