#+TITLE: Appunti totali globali nucleari
#+AUTHOR: Daniel Kertesz
#+EMAIL: daniel@spatof.org
#+DATE:      2011-06-21 Tue
#+DESCRIPTION: Appunti riguardanti Linux, UNIX in generale, OSX e altro.
#+KEYWORDS: appunti, linux, unix, osx, command-line
#+LANGUAGE:  it

* Version Control
** git

*** Ho creato un repository locale e lo voglio uppare in uno remoto

: git remote add origin foo.bar:repo.git=
: git push origin master:refs/heads/master

Oppure, alla /vecchia/ maniera:

1. Creare repository vuoto sul server

   : mkdir /var/git/myrepo.git && cd /var/git/myrepo.git
   : git --bare init

2. Aggiungere il repository remoto in locale

   : git remote add origin ssh://myserver.com/var/git/myrepo.git
   : git push origin master

3. /Track the remote branch/, per abilitare push e pull senza warning

   Editare .git/config:

   #+BEGIN_SRC conf
     [branch "master"]
             remote = origin
             merge = refs/heads/master
   #+END_SRC

*** UNDOing

L'undo di un =git add= e' =git reset=.
L'undo di un merge e' =git reset --merge=.


** bazaar

*** Branches, Shared Repositories, etc.

Informazioni dal manuale di bzr: [[http://doc.bazaar.canonical.com/latest/en/user-guide/organizing_branches.html][organizing_branches]]

Creazione di uno shared repository:
#+BEGIN_EXAMPLE
bzr init-repo PROJECT
cd PROJECT
bzr branch bzr+ssh://centralhost/srv/bzr/PROJECT/trunk
#+END_EXAMPLE

Creazione di /task branches/:
#+BEGIN_EXAMPLE
bzr branch trunk fix-123
cd fix-123
(hack, hack, hack)
#+END_EXAMPLE

* Excel

** Header per le colonne

Questo e' un barbatrucco, ma funziona. La riga *1* servira' per gli
header delle colonne, percio' converra' formattarla diversamente dalle
altre. Per poter scrollare il documento mantenendo la view sui nostri
header bisognera' selezionare la cella *A2* e cliccare dal menu'
_Window_ la checkbox *Freeze*.
Assicurarsi che la checkbox nel menu' _View_ *Column and row headers*
sia attiva.

* Bluetooth

** Tethering con aifone

: sudo /etc/rc.d/rc.bluetooth restart
*NOTA*: va fatto _dopo_ il boot, perche' c'e' di mezzo dbus e la merda
 slackware; a quel punto l'applet GNOME trovera' il device bluetooth.
Altre info su [[http://xn--9bi.net/2009/06/17/tethering-iphone-3-0-to-ubuntu-9-04/][internet]].

* Installazione ubuntu

Aggiornato a /natty/: 11.04.

- Utilizzare la ISO /alternate/ per avere a disposizione LVM + dm-crypt.
- +staccare il cavo di rete per installare dal cazzo di drive USB+
  Vuole la rete *per forza*.

** Partizionamento LVM + dm-crypt

1. Selezionare "Manual partitioning".
2. Creare una partizione *primaria* ext2 per /boot da *260MB*.
3. Creare una partizione *logica* con il resto del disco per LVM
   encrypted. Usare per "physical volume for LVM".
4. Configure encrypted volumes e selezionare la partizione grossa LVM.
5. Configure the logical volume manager.
   - Il physical volume e' la partizione grossa.
   - Un volume group e...
   - root 10gb
   - tmp 10gb
   - var 20gb
   - usr 50gb
   - opt 20gb
   - swap 4gb
   - home -- il resto
6. Assegnare le partizioni (use as ...) ai volumi LVM.

* Python

** Python e virtualenv

Assicurarsi *sempre* che gli script contengano

: #!/usr/bin/env python

e non:

: #!/usr/bin/python

Altrimenti /virtualenv/ non funzionera'. Il problema puo' accadere ad
esempio quando si creano nuovi progetti /Django/, perche' =manage.py=
contiene =#!/usr/bin/python=.
