; (setq piger/default-font "Input Mono 13")
(setq piger/default-font "Iosevka 15")
;; (setq piger/default-font "JetBrains Mono 13")
;; (setq piger/default-font "Victor Mono 13")
(setq piger/code-directories-alist '("~/code" "~/code/others"))
(setq piger/completion-system 'bedrock)
(setq piger/doom-themes-theme 'doom-earl-grey)
