(defun inspiration-724362 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/724362/"
  (interactive)
  (color-theme-install
   '(inspiration-724362
     ((background-color . "#000100")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#96403F"))))
     (font-lock-constant-face ((t (:foreground "#6A1A7B"))))
     (font-lock-builtin-face ((t (:foreground "#007EFC"))))
     (font-lock-function-name-face ((t (:foreground "#A37900"))))
     (font-lock-variable-name-face ((t (:foreground "#2BB12B"))))
     (font-lock-keyword-face ((t (:foreground "#575857"))))
     (font-lock-string-face ((t (:foreground "#823378"))))
     (font-lock-doc-string-face ((t (:foreground "#823378"))))
     (font-lock-type-face ((t (:foreground "#702D63"))))
     )))

(provide 'inspiration-724362)
