
(defun inspiration-278211 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/278211/"
  (interactive)
  (color-theme-install
   '(inspiration-278211
     ((background-color . "#FFFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#B4B615"))))
     (font-lock-constant-face ((t (:foreground "#C4B943"))))
     (font-lock-builtin-face ((t (:foreground "#A66293"))))
     (font-lock-function-name-face ((t (:foreground "#A30058"))))
     (font-lock-variable-name-face ((t (:foreground "#969A1E"))))
     (font-lock-keyword-face ((t (:foreground "#C86C87"))))
     (font-lock-string-face ((t (:foreground "#C97A00"))))
     (font-lock-doc-string-face ((t (:foreground "#C97A00"))))
     (font-lock-type-face ((t (:foreground "#CF0134"))))
     )))

(provide 'inspiration-278211)
