(defun inspiration-435050 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/435050/"
  (interactive)
  (color-theme-install
   '(inspiration-435050
     ((background-color . "#FEFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#961794"))))
     (font-lock-constant-face ((t (:foreground "#4D1822"))))
     (font-lock-builtin-face ((t (:foreground "#FF0048"))))
     (font-lock-function-name-face ((t (:foreground "#782B2A"))))
     (font-lock-variable-name-face ((t (:foreground "#186678"))))
     (font-lock-keyword-face ((t (:foreground "#165AC1"))))
     (font-lock-string-face ((t (:foreground "#610F21"))))
     (font-lock-doc-string-face ((t (:foreground "#610F21"))))
     (font-lock-type-face ((t (:foreground "#025A00"))))
     )))

(provide 'inspiration-435050)
