(defun inspiration-268935 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/268935/"
  (interactive)
  (color-theme-install
   '(inspiration-268935
     ((background-color . "#FEFFFF")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#EF5300"))))
     (font-lock-constant-face ((t (:foreground "#FF4B24"))))
     (font-lock-builtin-face ((t (:foreground "#D7154B"))))
     (font-lock-function-name-face ((t (:foreground "#45003B"))))
     (font-lock-variable-name-face ((t (:foreground "#FF0044"))))
     (font-lock-keyword-face ((t (:foreground "#640000"))))
     (font-lock-string-face ((t (:foreground "#AA0034"))))
     (font-lock-doc-string-face ((t (:foreground "#AA0034"))))
     (font-lock-type-face ((t (:foreground "#AE000F"))))
     )))

(provide 'inspiration-268935)
