(defun inspiration-733362 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/733362/"
  (interactive)
  (color-theme-install
   '(inspiration-733362
     ((background-color . "#000D00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#8FC85F"))))
     (font-lock-constant-face ((t (:foreground "#613689"))))
     (font-lock-builtin-face ((t (:foreground "#764373"))))
     (font-lock-function-name-face ((t (:foreground "#99AD22"))))
     (font-lock-variable-name-face ((t (:foreground "#BFFF00"))))
     (font-lock-keyword-face ((t (:foreground "#52913C"))))
     (font-lock-string-face ((t (:foreground "#C2603A"))))
     (font-lock-doc-string-face ((t (:foreground "#C2603A"))))
     (font-lock-type-face ((t (:foreground "#773769"))))
     )))

(provide 'inspiration-733362)
