(defun pigerrimitudo ()
  (interactive)
  (color-theme-install
   '(pigerrimitudo2
      ((background-color . "#f2f2f2")
      (background-mode . light)
      (border-color . "#d0d7f1")
      (cursor-color . "#231a1a")
      (foreground-color . "#2e2e2e")
      (mouse-color . "black"))
     (fringe ((t (:background "#d0d7f1"))))
     (mode-line ((t (:foreground "#ffffff" :background "#7d7d7d"))))
     (region ((t (:background "#d7eacd"))))
     (font-lock-builtin-face ((t (:foreground "#337880"))))
     (font-lock-comment-face ((t (:foreground "#7d827d"))))
     (font-lock-function-name-face ((t (:foreground "#19a1f5"))))
     (font-lock-keyword-face ((t (:foreground "#de401b"))))
     (font-lock-string-face ((t (:foreground "#931a25"))))
     (font-lock-type-face ((t (:foreground"#0ea40a"))))
     (font-lock-variable-name-face ((t (:foreground "#5c8807"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'pigerrimitudo2)

(defun pigerrimitudo ()
  (interactive)
  (color-theme-install
   '(pigerrimitudo
      ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#d0d7f1")
      (cursor-color . "#231a1a")
      (foreground-color . "#2e2e2e")
      (mouse-color . "black"))
     (fringe ((t (:background "#d0d7f1"))))
     (mode-line ((t (:foreground "#ffffff" :background "#7d7d7d"))))
     (region ((t (:background "#d7eacd"))))
     (font-lock-builtin-face ((t (:foreground "#337880"))))
     (font-lock-comment-face ((t (:foreground "#7d827d"))))
     (font-lock-function-name-face ((t (:foreground "#19a1f5"))))
     (font-lock-keyword-face ((t (:foreground "#de401b"))))
     (font-lock-string-face ((t (:foreground "#2c8a0f"))))
     (font-lock-type-face ((t (:foreground"#0ea40a"))))
     (font-lock-variable-name-face ((t (:foreground "#405b0b"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'pigerrimitudo)