# -*- mode: shell-script -*-
# zshenv
# This file is always executed by zsh so it's mostly useful to set environment
# variables used by non-interactive jobs.

# PATH handling {{{
# PATH and path refers to the same variable (tied), so as MANPATH and manpath.
# The attribute flag -U is to keep unique values inside an array.
typeset -U path manpath fpath cdpath

# set default PATH, keeping any existing system-wide PATH value.
path=(
    $path /sbin /bin /usr/sbin /usr/bin /usr/X11R6/bin 
    /usr/local/sbin /usr/local/bin
)

if [[ $OSTYPE = darwin* ]]; then
    # Homebrew
    [[ -d /usr/local/bin ]] && path=(/usr/local/bin $path)
fi

# Go support
if [[ -d $HOME/dev/go ]]; then
    export GOPATH=$HOME/dev/go
    path+=($HOME/dev/go/bin)
fi
[[ -d /usr/local/opt/go/libexec/bin ]] && path+=(/usr/local/opt/go/libexec/bin)

# Rust support
[[ -d $HOME/.cargo/bin ]] && path+=($HOME/.cargo/bin)

# Other miscellaneous bin directories.
# If you have a ~/bin directory, add it to PATH (here I use the path parameter
# instead of the PATH environment variable).
if [[ -d $HOME/bin ]]; then
    path+=$HOME/bin
elif [[ -d $HOME/Preferences/bin ]]; then
    path+=$HOME/Preferences/bin
fi
# same for ~/local
[[ -d $HOME/local/bin ]] && path+=$HOME/local/bin

[[ -d /opt/bin ]] && path+=/opt/bin
[[ -d /opt/local/bin ]] && path+=/opt/local/bin
[[ -d /usr/games ]] && path+=/usr/games

# Poetry
[[ -d $HOME/.poetry/bin ]] && path+=$HOME/.poetry/bin

# Plan9
if [[ -d /usr/local/plan9port ]]; then
    export PLAN9=/usr/local/plan9port
    path+=/usr/local/plan9port/bin
fi
# }}}

# ripgrep
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc

# Use ssh for any remote operation involving CVS or rsync
export CVS_RSH="ssh"
export RSYNC_RSH="ssh"

# Format string for 'time' command:
TIMEFMT="%*E real time :: CPU: %P (%U user, %S kernel) :: %J"

# Set the umask
if [[ $UID == 0 ]]; then
    umask 077
else
    umask u=rwx,g=rx,o=
fi

# 11/06/2016
# Not having an umask of "022" breaks tools written by the cool kids (like kitchen)
umask 022

# Alias vim and gvim to have it working inside shell functions and such.
# See also: zsh/os/darwin
foreach macvim (/Applications/MacVim.app ~/Applications/MacVim.app); do
  if [[ -e $macvim ]]; then
      alias vim="$macvim/Contents/MacOS/Vim"
      alias gvim="$macvim/Contents/MacOS/MacVim"
      break
  fi
done

# on macOS /etz/profile will call /usr/libexec/path_helper which will fuck PATH ignoring
# everything done so far.
# Also if we ever need to have this feature we can just read files in /etc/paths.d and /etc/manpaths.d by
# ourselves; see man 'path_helper'.
setopt no_GLOBAL_RCS

# Load local zshenv
[[ -f $HOME/.zshenv.local ]] && source $HOME/.zshenv.local

# vim: ft=zsh
