# Verifies that all the packages mentioned in Brewfile are installable.

name: Verify Brewfile

on:
  push:
    branches: master
  pull_request:

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install all the packages in Brewfile
        run: brew bundle install --file Brewfile
