(defun inspiration-303711 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/303711/"
  (interactive)
  (color-theme-install
   '(inspiration-303711
     ((background-color . "#FFFFF5")
      (foreground-color . "#000000")
      (background-mode . bright)
      (border-color . "#C8C8C8")
      (cursor-color . "#000000")
      (mouse-color . "#C8C8C8"))
     (mode-line ((t (:foreground "#000000" :background "#C8C8C8"))))
     (region ((t (:background "#C8C8C8"))))

     (font-lock-comment-face ((t (:foreground "#262300"))))
     (font-lock-constant-face ((t (:foreground "#C60063"))))
     (font-lock-builtin-face ((t (:foreground "#B400F4"))))
     (font-lock-function-name-face ((t (:foreground "#8CC000"))))
     (font-lock-variable-name-face ((t (:foreground "#A67400"))))
     (font-lock-keyword-face ((t (:foreground "#D35400"))))
     (font-lock-string-face ((t (:foreground "#C48E10"))))
     (font-lock-doc-string-face ((t (:foreground "#C48E10"))))
     (font-lock-type-face ((t (:foreground "#B0C43D"))))
     )))

(provide 'inspiration-303711)
