(defun inspiration-961925 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/961925/"
  (interactive)
  (color-theme-install
   '(inspiration-961925
     ((background-color . "#00040F")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#994E16"))))
     (font-lock-constant-face ((t (:foreground "#84560C"))))
     (font-lock-builtin-face ((t (:foreground "#BD7C00"))))
     (font-lock-function-name-face ((t (:foreground "#37C239"))))
     (font-lock-variable-name-face ((t (:foreground "#1ABD2A"))))
     (font-lock-keyword-face ((t (:foreground "#C02B4A"))))
     (font-lock-string-face ((t (:foreground "#3AAF0B"))))
     (font-lock-doc-string-face ((t (:foreground "#3AAF0B"))))
     (font-lock-type-face ((t (:foreground "#4A815B"))))
     )))

(provide 'inspiration-961925)
