(defun inspiration-965049 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/965049/"
  (interactive)
  (color-theme-install
   '(inspiration-965049
     ((background-color . "#000001")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#BC9908"))))
     (font-lock-constant-face ((t (:foreground "#E05F68"))))
     (font-lock-builtin-face ((t (:foreground "#661A79"))))
     (font-lock-function-name-face ((t (:foreground "#005FA3"))))
     (font-lock-variable-name-face ((t (:foreground "#84CD88"))))
     (font-lock-keyword-face ((t (:foreground "#6F7805"))))
     (font-lock-string-face ((t (:foreground "#845BCD"))))
     (font-lock-doc-string-face ((t (:foreground "#845BCD"))))
     (font-lock-type-face ((t (:foreground "#0C0CFF"))))
     )))

(provide 'inspiration-965049)
