(defun inspiration-759815 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/759815/"
  (interactive)
  (color-theme-install
   '(inspiration-759815
     ((background-color . "#001600")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#AB71FF"))))
     (font-lock-constant-face ((t (:foreground "#FFA1DB"))))
     (font-lock-builtin-face ((t (:foreground "#F1AE9F"))))
     (font-lock-function-name-face ((t (:foreground "#E37C96"))))
     (font-lock-variable-name-face ((t (:foreground "#FFFCFF"))))
     (font-lock-keyword-face ((t (:foreground "#4AABFF"))))
     (font-lock-string-face ((t (:foreground "#915CA8"))))
     (font-lock-doc-string-face ((t (:foreground "#915CA8"))))
     (font-lock-type-face ((t (:foreground "#BFAEFF"))))
     )))

(provide 'inspiration-759815)
